#!/usr/bin/env python3
"""Generate torch.profiler instrumentation for vLLM pods.

torch.profiler only profiles the process it runs in — you can't attach from
outside. This tool generates startup wrappers and prints profiling commands;
it does not modify deployments directly.

Usage (from your workstation):

    # Option 1: Generate a startup wrapper
    python3 torch_profiler.py wrapper --duration 30 --output /tmp/profile_wrapper.py
    # Copy to pod, then restart vLLM with: python3 /tmp/profile_wrapper.py <original vllm args>

    # Option 2: Use Nsight Systems (profiles GPU from outside, no code changes)
    python3 torch_profiler.py nsys-cmd --pod POD --namespace NS --duration 10

    # Option 3: Generate env vars for PyTorch's built-in kineto profiler
    python3 torch_profiler.py kineto-env
"""

import argparse
import sys

_WRAPPER_TEMPLATE = '''\
#!/usr/bin/env python3
"""vLLM startup wrapper with torch.profiler instrumentation.

Generated by llm-d diagnostics toolkit profiling/torch_profiler.py.
Wraps the vLLM entrypoint with a profiler that captures the first N
seconds of serving after model load completes.

Usage:
    python3 /tmp/profile_wrapper.py --model my-model --port 8000 [other vllm args]

The trace is written to {trace_dir}/trace_<timestamp>.json.
View in https://ui.perfetto.dev
"""
import os
import sys
import threading
import time


def _start_profiler(duration, trace_dir):
    """Start profiler after a delay (lets model loading finish)."""
    import torch.profiler

    os.makedirs(trace_dir, exist_ok=True)
    output = os.path.join(trace_dir, f"trace_{{int(time.time())}}.json")

    activities = [torch.profiler.ProfilerActivity.CPU]
    try:
        if __import__("torch").cuda.is_available():
            activities.append(torch.profiler.ProfilerActivity.CUDA)
    except Exception:
        pass

    print(f"[profiler] Starting {{duration}}s capture → {{output}}", flush=True)

    with torch.profiler.profile(
        activities=activities,
        record_shapes={record_shapes},
        profile_memory={profile_memory},
        with_stack={with_stack},
    ) as prof:
        time.sleep(duration)

    prof.export_chrome_trace(output)
    size_mb = os.path.getsize(output) / (1024 * 1024)
    print(f"[profiler] Trace saved: {{output}} ({{size_mb:.1f}} MB)", flush=True)


# Schedule profiler to start after model is loaded
_profiler_thread = threading.Thread(
    target=_start_profiler,
    args=({duration}, "{trace_dir}"),
    daemon=True,
)

# Delay start — model loading takes 30-120s typically
def _delayed_start(delay={startup_delay}):
    print(f"[profiler] Waiting {{delay}}s for model load before profiling...", flush=True)
    time.sleep(delay)
    _profiler_thread.start()

threading.Thread(target=_delayed_start, daemon=True).start()

# Run vLLM's actual entrypoint via runpy — same as `python -m vllm.entrypoints.openai.api_server`.
# This avoids assumptions about the internal API signature (which changes across vLLM versions).
import runpy
sys.argv = sys.argv[1:]  # Remove this wrapper script from argv
runpy.run_module("vllm.entrypoints.openai.api_server", run_name="__main__")
'''


def cmd_wrapper(args: argparse.Namespace) -> None:
    code = _WRAPPER_TEMPLATE.format(
        duration=args.duration,
        trace_dir=args.trace_dir,
        startup_delay=args.startup_delay,
        record_shapes=args.record_shapes,
        profile_memory=args.profile_memory,
        with_stack=args.with_stack,
    )
    if args.output:
        with open(args.output, "w") as f:
            f.write(code)
        print(f"Wrapper written to {args.output}")
        print(f"Copy to pod and run: python3 {args.output} <vllm args>")
    else:
        print(code)


def cmd_nsys(args: argparse.Namespace) -> None:
    print("# Profile vLLM GPU activity with Nsight Systems")
    print("# (requires nsys installed in the container image)")
    print()
    print(f"# 1. Exec into pod and run nsys on the vLLM process:")
    print(f"oc exec {args.pod} -n {args.namespace} -- bash -c '\\")
    print(f"  VLLM_PID=$(pgrep -f \"vllm.entrypoints\") && \\")
    print(f"  nsys profile --duration={args.duration} --output=/tmp/vllm_profile \\")
    print(f"    --trace=cuda,nvtx,osrt --target-processes=all \\")
    print(f"    --attach-pid=$VLLM_PID'")
    print()
    print(f"# 2. Copy report back:")
    print(f"oc cp {args.namespace}/{args.pod}:/tmp/vllm_profile.nsys-rep ./")
    print()
    print("# 3. View in Nsight Systems UI or convert to SQLite:")
    print("nsys stats ./vllm_profile.nsys-rep")


def cmd_kineto(args: argparse.Namespace) -> None:
    print("# PyTorch Kineto profiling via TORCH_TRACE")
    print("# Kineto is the underlying tracing engine inside torch.profiler.")
    print("# There are no user-facing KINETO_* env vars — use TORCH_TRACE instead.")
    print()
    ns = f" -n {args.namespace}" if args.namespace else ""
    print("# Enable Kineto trace collection on your deployment:")
    print(f"oc set env deployment/{args.deployment}{ns} \\")
    print(f"  TORCH_TRACE=/tmp/kineto_traces")
    print()
    print("# After collecting requests, copy traces and parse with tlparse:")
    print(f"# oc cp <ns>/<pod>:/tmp/kineto_traces/ ./kineto_traces/")
    print(f"# python3 profiling/tlparse_runner.py parse ./kineto_traces/")
    print()
    print("# For richer profiling (record_shapes, memory, stacks), use the")
    print("# 'wrapper' subcommand — it gives full torch.profiler control.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate torch.profiler instrumentation for vLLM pods"
    )
    sub = parser.add_subparsers(dest="command")

    wrapper = sub.add_parser(
        "wrapper", help="Generate a vLLM startup wrapper with profiling"
    )
    wrapper.add_argument(
        "--duration", type=float, default=30.0,
        help="Profiling capture duration in seconds (default: 30)",
    )
    wrapper.add_argument(
        "--startup-delay", type=float, default=60.0,
        help="Seconds to wait for model load before profiling (default: 60)",
    )
    wrapper.add_argument(
        "--trace-dir", default="/tmp/torch_traces",
        help="Directory for trace output (default: /tmp/torch_traces)",
    )
    wrapper.add_argument(
        "--output", "-o", help="Write wrapper to file (default: stdout)",
    )
    wrapper.add_argument("--record-shapes", action="store_true", default=False)
    wrapper.add_argument("--profile-memory", action="store_true", default=False)
    wrapper.add_argument("--with-stack", action="store_true", default=False)

    nsys = sub.add_parser(
        "nsys-cmd", help="Print nsys commands to profile a running vLLM pod"
    )
    nsys.add_argument("--pod", required=True, help="Pod name")
    nsys.add_argument("-n", "--namespace", required=True, help="Namespace")
    nsys.add_argument("--duration", type=int, default=10, help="Capture seconds")

    kineto = sub.add_parser(
        "kineto-env", help="Print Kineto profiler env vars"
    )
    kineto.add_argument("--deployment", default="vllm-decode", help="Deployment name")
    kineto.add_argument("-n", "--namespace", help="Namespace")

    args = parser.parse_args()
    if args.command == "wrapper":
        cmd_wrapper(args)
    elif args.command == "nsys-cmd":
        cmd_nsys(args)
    elif args.command == "kineto-env":
        cmd_kineto(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
