apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  labels:
    app.kubernetes.io/part-of: vllm-disagg
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
