apiVersion: v1
kind: Service
metadata:
  name: vllm-prefill-svc
  labels:
    app: vllm-prefill
    app.kubernetes.io/part-of: vllm-disagg
spec:
  clusterIP: None
  selector:
    app: vllm-prefill
  ports:
  - name: http
    port: 8100
    targetPort: 8100
    protocol: TCP
  - name: nixl
    port: 5600
    targetPort: 5600
    protocol: TCP
